#####################################################################
### Michael Creutzinger                                           ###
### Colorado State University                                     ###
### November 15th, 2022                                           ###
### Project: Plot Creation                                        ###
###                                                               ###
###   Recreates the figure of simulation models generated by use  ###
### of Ojo et al. (2021) package `fdaoutlier`.                    ###
#####################################################################




## Setup steps
#####################################################################
# Libraries
library(tidyverse)
library(ggplot2)
library(fda)
library(fdaoutlier)
library(ggthemes)
library(gridExtra)

# Directory paths
dir_path <- file.path(here::here(), "R Code")

# Source scripts needed for plots
source(file = file.path(dir_path, "simulation_model_b.R"))
source(file = file.path(dir_path, "simulation_model_b_only.R"))
#####################################################################




## Recreates Figure 1 in the Introduction (Section 1)
#####################################################################
## Ojo data models
model_list <- vector("list", 9)
plot_colors <- c("lightgray", "red")
for (i in 1:9) {
  sim_mod_fct <- match.fun(paste0("simulation_model", i))
  model_temp <- sim_mod_fct()
  model_data_temp <- t(model_temp$data) %>%
    as.data.frame() %>%
    dplyr::mutate(t = 1:50) %>%
    tidyr::pivot_longer(-t, names_to = "Obs", values_to = "Value") %>%
    dplyr::mutate(Out = case_when(
      Obs %in% paste0("V", model_temp$true_outliers) ~ "Outlier",
      TRUE ~ "None"))
  
  model_list[[i]] <- ggplot() + 
    geom_line(aes(x = t, y = Value, group = Obs), 
              color = "lightgrey",
              data = model_data_temp %>% filter(Out == "None")) +
    geom_line(aes(x = t, y = Value, group = Obs), 
              color = "darkorange2",
              data = model_data_temp %>% filter(Out == "Outlier")) +
    guides(color = "none") +
    labs(title = paste0("Simulation Model ", i)) +
    theme_bw() +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          panel.background = element_blank())
}  

do.call("grid.arrange", c(model_list, ncol = 3))
#####################################################################



## Recreates Figures 6 and 7 in Appendix A
#####################################################################
# Figure 6
simulation_modelB2(cov_beta = .9, plot = T)

# Figure 7
simulation_modelB(cov_beta = .9, plot = T, n = 100)
#####################################################################